name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Optional: Ensure the dist directory exists
      - name: Create output folder
        run: mkdir -p dist

      # Snake Animation
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: phganie
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
